name: Hello World Action (rollup)
description: An action that was bundled together using rollup

author: luxass
branding:
  color: purple
  icon: package

runs:
  using: node20
  main: dist/index.cjs
