packages:
  - actions/**
catalog:
  "@actions/core": ^1.11.1
  "@luxass/eslint-config": ^4.14.0
  "@rollup/plugin-commonjs": ^28.0.2
  "@rollup/plugin-json": ^6.1.0
  "@rollup/plugin-node-resolve": ^16.0.0
  "@rollup/plugin-typescript": ^12.1.2
  "@rspack/cli": 1.2.2
  "@rspack/core": 1.2.2
  "@types/node": ^20.17.6
  "@vercel/ncc": ^0.38.3
  bunchee: ^6.2.0
  esbuild: ^0.24.2
  eslint: ^9.17.0
  eslint-plugin-format: ^0.1.3
  rolldown: 1.0.0-beta.3
  rollup: ^4.29.1
  ts-loader: ^9.5.1
  tslib: ^2.8.1
  tsup: ^8.3.5
  turbo: ^2.3.3
  typescript: ^5.7.2
  vite: ^6.0.6
  webpack: ^5.97.1
  webpack-cli: ^6.0.1
