packages:
  - actions/**

catalogs:
  # bunchee specific dependencies
  bunchee-bundler:
    bunchee: ^6.6.0

  # general dev dependencies
  dev:
    "@luxass/eslint-config": ^5.3.1
    "@types/node": ^22.18.3
    eslint: ^9.35.0
    eslint-plugin-format: ^1.0.1
    turbo: ^2.5.6
    typescript: ^5.9.2

  # esbuild specific dependencies
  esbuild-bundler:
    esbuild: ^0.25.9

  # ncc specific dependencies
  ncc-bundler:
    "@vercel/ncc": ^0.38.3

  # prod dependencies
  prod:
    "@actions/core": ^1.11.1

  # rolldown specific dependencies
  rolldown-bundler:
    rolldown: ^1.0.0-beta

  # rollup specific dependencies
  rollup-bundler:
    "@rollup/plugin-commonjs": ^28.0.6
    "@rollup/plugin-json": ^6.1.0
    "@rollup/plugin-node-resolve": ^16.0.1
    "@rollup/plugin-typescript": ^12.1.4
    rollup: ^4.50.1
    tslib: ^2.8.1

  # rspack specific dependencies
  rspack-bundler:
    "@rspack/cli": ^1.5.3
    "@rspack/core": ^1.5.3

  # tsup specific dependencies
  tsup-bundler:
    tsup: ^8.5.0

  # vite specific dependencies
  vite-bundler:
    vite: ^7.0.7

  # webpack specific dependencies
  webpack-bundler:
    ts-loader: ^9.5.4
    webpack: ^5.101.3
    webpack-cli: ^6.0.1

onlyBuiltDependencies:
  - "@swc/core"
  - esbuild
