packages:
  - actions/**
catalog:
  "@actions/core": ^1.11.1
  "@luxass/eslint-config": ^4.15.0
  "@rollup/plugin-commonjs": ^28.0.2
  "@rollup/plugin-json": ^6.1.0
  "@rollup/plugin-node-resolve": ^16.0.0
  "@rollup/plugin-typescript": ^12.1.2
  "@rspack/cli": 1.2.7
  "@rspack/core": 1.2.7
  "@types/node": ^22.0.0
  "@vercel/ncc": ^0.38.3
  bunchee: ^6.3.4
  esbuild: ^0.25.0
  eslint: ^9.20.1
  eslint-plugin-format: ^1.0.1
  rolldown: 1.0.0-beta.3
  rollup: ^4.34.6
  ts-loader: ^9.5.2
  tslib: ^2.8.1
  tsup: ^8.3.6
  turbo: ^2.4.2
  typescript: ^5.7.3
  vite: ^6.1.0
  webpack: ^5.97.1
  webpack-cli: ^6.0.1
  "@manypkg/cli": ^0.23.0
