packages:
  - actions/**

catalogs:
  # bunchee specific dependencies
  bunchee-bundler:
    bunchee: ^6.5.4

  # general dev dependencies
  dev:
    "@luxass/eslint-config": ^5.1.0
    "@types/node": ^22.0.0
    eslint: ^9.30.1
    eslint-plugin-format: ^1.0.1
    turbo: ^2.5.4
    typescript: ^5.8.3

  # esbuild specific dependencies
  esbuild-bundler:
    esbuild: ^0.25.5

  # ncc specific dependencies
  ncc-bundler:
    "@vercel/ncc": ^0.38.3

  # prod dependencies
  prod:
    "@actions/core": ^1.11.1

  # rolldown specific dependencies
  rolldown-bundler:
    rolldown: ^1.0.0-beta.23

  # rollup specific dependencies
  rollup-bundler:
    "@rollup/plugin-commonjs": ^28.0.6
    "@rollup/plugin-json": ^6.1.0
    "@rollup/plugin-node-resolve": ^16.0.1
    "@rollup/plugin-typescript": ^12.1.4
    rollup: ^4.44.1
    tslib: ^2.8.1

  # rspack specific dependencies
  rspack-bundler:
    "@rspack/cli": ^1.4.2
    "@rspack/core": ^1.4.2

  # tsup specific dependencies
  tsup-bundler:
    tsup: ^8.5.0

  # vite specific dependencies
  vite-bundler:
    vite: ^7.0.1

  # webpack specific dependencies
  webpack-bundler:
    ts-loader: ^9.5.2
    webpack: ^5.99.9
    webpack-cli: ^6.0.1

onlyBuiltDependencies:
  - "@swc/core"
  - esbuild
