packages:
  - actions/**
catalog:
  "@actions/core": ^1.11.1
  "@luxass/eslint-config": ^4.18.1
  "@rollup/plugin-commonjs": ^28.0.3
  "@rollup/plugin-json": ^6.1.0
  "@rollup/plugin-node-resolve": ^16.0.1
  "@rollup/plugin-typescript": ^12.1.2
  "@rspack/cli": 1.3.2
  "@rspack/core": 1.3.2
  "@types/node": ^22.0.0
  "@vercel/ncc": ^0.38.3
  bunchee: ^6.5.0
  esbuild: ^0.25.2
  eslint: ^9.24.0
  eslint-plugin-format: ^1.0.1
  rolldown: 1.0.0-beta.7
  rollup: ^4.39.0
  ts-loader: ^9.5.2
  tslib: ^2.8.1
  tsup: ^8.4.0
  turbo: ^2.5.0
  typescript: ^5.8.3
  vite: ^6.1.4
  webpack: ^5.98.0
  webpack-cli: ^6.0.1
  "@manypkg/cli": ^0.23.0
