packages:
  - actions/**

catalogs:
  # bunchee specific dependencies
  bunchee-bundler:
    bunchee: ^6.5.0

  # general dev dependencies
  dev:
    "@luxass/eslint-config": ^4.18.1
    "@types/node": ^22.0.0
    eslint: ^9.24.0
    eslint-plugin-format: ^1.0.1
    turbo: ^2.5.0
    typescript: ^5.8.3

  # esbuild specific dependencies
  esbuild-bundler:
    esbuild: ^0.25.2

  # ncc specific dependencies
  ncc-bundler:
    "@vercel/ncc": ^0.38.3

  # prod dependencies
  prod:
    "@actions/core": ^1.11.1

  # rolldown specific dependencies
  rolldown-bundler:
    rolldown: ^1.0.0-beta.7

  # rollup specific dependencies
  rollup-bundler:
    "@rollup/plugin-commonjs": ^28.0.3
    "@rollup/plugin-json": ^6.1.0
    "@rollup/plugin-node-resolve": ^16.0.1
    "@rollup/plugin-typescript": ^12.1.2
    rollup: ^4.39.0
    tslib: ^2.8.1

  # rspack specific dependencies
  rspack-bundler:
    "@rspack/cli": ^1.3.2
    "@rspack/core": ^1.3.2

  # tsup specific dependencies
  tsup-bundler:
    tsup: ^8.4.0

  # vite specific dependencies
  vite-bundler:
    vite: ^6.2.5

  # webpack specific dependencies
  webpack-bundler:
    ts-loader: ^9.5.2
    webpack: ^5.98.0
    webpack-cli: ^6.0.1

onlyBuiltDependencies:
  - "@swc/core"
  - esbuild
