packages:
  - actions/**

catalogs:
  # bunchee specific dependencies
  bunchee-bundler:
    bunchee: 6.10.0

  # general dev dependencies
  dev:
    "@luxass/eslint-config": 7.4.2
    "@types/node": 22.19.17
    eslint: 10.0.3
    eslint-plugin-format: 2.0.1
    turbo: 2.9.6
    typescript: 5.9.3

  # esbuild specific dependencies
  esbuild-bundler:
    esbuild: 0.28.0

  # ncc specific dependencies
  ncc-bundler:
    "@vercel/ncc": 0.38.4

  # prod dependencies
  prod:
    "@actions/core": 3.0.1

  # rolldown specific dependencies
  rolldown-bundler:
    rolldown: 1.0.0-rc.18

  # rollup specific dependencies
  rollup-bundler:
    "@rollup/plugin-commonjs": 29.0.2
    "@rollup/plugin-json": 6.1.0
    "@rollup/plugin-node-resolve": 16.0.3
    "@rollup/plugin-typescript": 12.3.0
    rollup: 4.60.2
    tslib: 2.8.1

  # rspack specific dependencies
  rspack-bundler:
    "@rspack/cli": 1.7.11
    "@rspack/core": 1.7.11

  # tsup specific dependencies
  tsup-bundler:
    tsup: 8.5.1

  # vite specific dependencies
  vite-bundler:
    vite: 8.0.0

  # webpack specific dependencies
  webpack-bundler:
    ts-loader: 9.5.7
    webpack: 5.106.2
    webpack-cli: 7.0.2

onlyBuiltDependencies:
  - "@swc/core"
  - esbuild

overrides:
  rolldown: catalog:rolldown-bundler
