packages:
  - actions/**

catalogs:
  # bunchee specific dependencies
  bunchee-bundler:
    bunchee: 6.9.3

  # general dev dependencies
  dev:
    "@luxass/eslint-config": 6.0.3
    "@types/node": 22.18.6
    eslint: 9.39.2
    eslint-plugin-format: 1.3.1
    turbo: 2.7.3
    typescript: 5.9.3

  # esbuild specific dependencies
  esbuild-bundler:
    esbuild: 0.27.2

  # ncc specific dependencies
  ncc-bundler:
    "@vercel/ncc": 0.38.4

  # prod dependencies
  prod:
    "@actions/core": 2.0.2

  # rolldown specific dependencies
  rolldown-bundler:
    rolldown: 1.0.0-beta.59

  # rollup specific dependencies
  rollup-bundler:
    "@rollup/plugin-commonjs": 29.0.0
    "@rollup/plugin-json": 6.1.0
    "@rollup/plugin-node-resolve": 16.0.3
    "@rollup/plugin-typescript": 12.3.0
    rollup: 4.55.1
    tslib: 2.8.1

  # rspack specific dependencies
  rspack-bundler:
    "@rspack/cli": 1.7.1
    "@rspack/core": 1.7.1

  # tsup specific dependencies
  tsup-bundler:
    tsup: 8.5.1

  # vite specific dependencies
  vite-bundler:
    vite: 7.3.1

  # webpack specific dependencies
  webpack-bundler:
    ts-loader: 9.5.4
    webpack: 5.104.1
    webpack-cli: 6.0.1

onlyBuiltDependencies:
  - "@swc/core"
  - esbuild

overrides:
  rolldown: catalog:rolldown-bundler
