name: "Publish VS Code Extension"
description: "An action to publish Visual Studio Code Extension to Open VSX Registry or Visual Studio Marketplace"

author: luxass
branding:
  color: purple
  icon: package

runs:
  using: node20
  main: "dist/index.js"
