name: Hello World Action (ESBuild)
description: An action that was bundled together using ESBuild

author: luxass
branding:
  color: purple
  icon: package

runs:
  using: node20
  main: dist/index.js
