name: Hello World Action (esbuild)
description: An action that was bundled together using esbuild

inputs:
  github-token:
    description: GitHub Token
    required: true
    default: ${{ github.token }}

author: luxass
branding:
  color: purple
  icon: package

runs:
  using: node20
  main: dist/index.js
