name: CI

on:
  push:
  pull_request:
    types: [opened, synchronize]

env:
  NODE_VERSION: 16

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    strategy:
      fail-fast: true
    steps:
      - uses: actions/checkout@v3
      - name: AA
        uses: ./
        
